package org.omg.PortableServer;


/**
* org/omg/PortableServer/IMPLICIT_ACTIVATION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON/workspace/8-2-build-linux-amd64/jdk8u65/4987/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 6, 2015 5:16:50 PM PDT
*/

public interface IMPLICIT_ACTIVATION_POLICY_ID
{

  /**
  	 * The value representing IMPLICIT_ACTIVATION_POLICY_ID.
  	 */
  public static final int value = (int)(20L);
}
